### ISSUE TITLE
missing days

### ISSUE THREAD

**Issue by friep** [MKyhos/adventofcode#1]
solutions for days:

- [ ] 5
- [ ] 8
- [ ] 9
- [ ] 10
- [ ] 11
- [ ] 12
- [ ] 13
- [ ] 14
- [ ] 16
- [ ] 17
- [ ] 18
- [ ] 19
- [ ] 20
- [ ] 21
- [ ] 22
- [ ] 23
- [ ] 24
- [ ] 25

thanks.

**Comment by MKyhos** [comment]
Hello @friep,
thank you very much for submitting this well-written issue. Could you probably add a reprex?
Also, please see the [community guidelines](https://www.youtube.com/watch?v=dQw4w9WgXcQ) for collaborating on this repository.

Thank you very much and have a nice day! :pray:

**Comment by MKyhos** [comment]
On a second thought, the maintaining team has voted against addressing this issue.
